### ISSUE TITLE
Add Sprint Boot

### ISSUE THREAD

**Issue by wangxiangtao** [elsevierlabs-os/soda#1]
Add sprint boot ,   change the WebConfig.scala to WebApplication.scala  and delete web.xml

It will start the embed server after run the main method from WebApplication.scala without manually copy the war to Jetty.  
It will be convenient for debug and deploy.  

[soda-sprint-boot.zip](https://github.com/elsevierlabs-os/soda/files/61409/soda-sprint-boot.zip)

**Comment by sujitpal** [comment]
I decided against including this, main reason being that I am not familiar with sprint boot and it would be hard for me to maintain.
