### ISSUE TITLE
upstream SolrTextTagger_patch.txt

### ISSUE THREAD

**Issue by dsmiley** [elsevierlabs-os/soda#11]
I see the file SolrTextTagger_patch.txt where you allow a zero-length token.  Perhaps this should be upstreamed to the SolrTextTagger if this is valid?  It could simply log at debug level.

**Comment by dsmiley** [comment]
FWIW I plan to bring the SolrTextTagger into Apache Lucene/Solr.  SoDA would probably then like to use the one in Solr to make things simpler.  It'd be more convenient if the `SolrTextTagger_patch.txt` is considered/addressed now rather than after... but we can still do after.

**Comment by sujitpal** [comment]
I am hoping to upgrade to Solr 7.5 and SolrTextTagger 2.6-SNAPSHOT based on the experiment I ran with postingsFormat=FST50, so hopefully this will no longer be needed. If it is I will submit a patch.

**Comment by sujitpal** [comment]
This doesn't seem to be needed anymore, at least with the use cases I have tried. Closing it.
