### ISSUE TITLE
war file name

### ISSUE THREAD

**Issue by OoDeLally** [elsevierlabs-os/soda#4]
If we want the app to be available at `http://public_ip:8080/soda/index.json`

then we should rename `soda-1.0-SNAPSHOT.war` to `soda.war`:

```cp target/scala-2.10/soda-1.0-SNAPSHOT.war ../jetty-9.2.11/webapps/soda.war```

**Comment by sujitpal** [comment]
Thank you @OoDeLally, on vacation this week, will update the docs and close next week.

**Comment by sujitpal** [comment]
Docs updated and pushed to head, closing.
