### ISSUE TITLE
Character indexes shifted when using special UTF8 symbols

### ISSUE THREAD

**Issue by OoDeLally** [elsevierlabs-os/soda#7]
When annotating the following term: `He mentionned ’Obama’ in the White House`, here is the result:
```[
  {
    begin: 17, // Expected 15
    confidence: "1.0",
    coveredText: "Obama",
    end: 22,
    id: "Obama",
    lexicon: "person",
  },
  {
    begin: 43, // Expected 39
    confidence: "1.0",
    coveredText: "White House",
    end: 54,
    id: "White House",
    lexicon: "place",
  }
]
```

The character `’` seems to be counted as 3 characters.
Checking the utf8 reference, I can see that this character is 3-bytes-long:
```
UTF-8 (hex) | 0xE2 0x80 0x99 (e28099)
```

I can imagine it to behave this way for any multi-byte utf8 characters.
The begining and end should indicate the index on characters, not on bytes.

Thank you

**Comment by sujitpal** [comment]
SoDA just reports the offsets returned from SolrTextTagger. Looking at the [configuration documentation for SolrTextTagger](https://github.com/OpenSextant/SolrTextTagger#configuration), I see that it requires you to pass your query (document) and index (dictionaries) through AsciiFoldingFilterFactory, which should have converted the MS-quote into a ascii quote. Can you verify if you are using this filter in your configuration?

**Comment by OoDeLally** [comment]
Hello @sujitpal,
Thank you for your answer. I wasnt aware of that recommendation. I guess it solves it.
I actually now commit normalized text, so I dont have that problem anymore.
Thank you

**Comment by dsmiley** [comment]
It should not be considered _required_ to use AsciiFoldingFilterFactory!  I added a new test to the SolrTextTagger that tests that the offsets are as they should be for the example presented in this issue using the "Right Single Quotation Mark" U+2019.  This counts as one character in UTF16.

The offsets returned by the SolrTextTagger are UTF16 characters (i.e. Java/JVM character).  For languages communicating with the text tagger that aren't written in Java, there may be a mismatch if the "characters" of the language in question isn't based on the same definition.  Here's some interesting discussion on the matter: https://issues.apache.org/jira/browse/SOLR-1954?focusedCommentId=12880360&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12880360
Here is an example of a Unicode character that counts as two UTF16 characters: https://unicode-table.com/en/29B05/
